routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AppsController;
use App\Http\Controllers\UserInterfaceController;
use App\Http\Controllers\CardsController;
use App\Http\Controllers\ComponentsController;
use App\Http\Controllers\ExtensionController;
use App\Http\Controllers\PageLayoutController;
use App\Http\Controllers\FormsController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\MiscellaneousController;
use App\Http\Controllers\AuthenticationController;
use App\Http\Controllers\ChartsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Main Page Route
Route::group(['middleware' => 'auth:sanctum', 'verified'],function(){
    Route::get('/', [DashboardController::class, 'dashboardDocumentManagement'])->name('dashboard-documents');
});


/* Route Dashboards */
Route::group(['prefix' => 'dashboard'], function () {
    Route::get('analytics', [DashboardController::class, 'dashboardAnalytics'])->name('dashboard-analytics');
    Route::get('ecommerce', [DashboardController::class, 'dashboardEcommerce'])->name('dashboard-ecommerce');
});
/* Route Dashboards */

require __DIR__ . '/web/customer.php';
require __DIR__ . '/web/setting.php';
require __DIR__ . '/web/document.php';

/* Route Apps */
Route::group(['prefix' => 'app'], function () {
    Route::get('email', [AppsController::class, 'emailApp'])->name('app-email');
    Route::get('chat', [AppsController::class, 'chatApp'])->name('app-chat');
    Route::get('todo', [AppsController::class, 'todoApp'])->name('app-todo');
    Route::get('calendar', [AppsController::class, 'calendarApp'])->name('app-calendar');
    Route::get('kanban', [AppsController::class, 'kanbanApp'])->name('app-kanban');
    Route::get('invoice/list', [AppsController::class, 'invoice_list'])->name('app-invoice-list');
    Route::get('invoice/preview', [AppsController::class, 'invoice_preview'])->name('app-invoice-preview');
    Route::get('invoice/edit', [AppsController::class, 'invoice_edit'])->name('app-invoice-edit');
    Route::get('invoice/add', [AppsController::class, 'invoice_add'])->name('app-invoice-add');
    Route::get('invoice/print', [AppsController::class, 'invoice_print'])->name('app-invoice-print');
    Route::get('ecommerce/shop', [AppsController::class, 'ecommerce_shop'])->name('app-ecommerce-shop');
    Route::get('ecommerce/details', [AppsController::class, 'ecommerce_details'])->name('app-ecommerce-details');
    Route::get('ecommerce/wishlist', [AppsController::class, 'ecommerce_wishlist'])->name('app-ecommerce-wishlist');
    Route::get('ecommerce/checkout', [AppsController::class, 'ecommerce_checkout'])->name('app-ecommerce-checkout');
    Route::get('file-manager', [AppsController::class, 'file_manager'])->name('app-file-manager');
    Route::get('access-roles', [AppsController::class, 'access_roles'])->name('app-access-roles');
    Route::get('access-permission', [AppsController::class, 'access_permission'])->name('app-access-permission');
    Route::get('user/list', [AppsController::class, 'user_list'])->name('app-user-list');
    Route::get('user/view/account', [AppsController::class, 'user_view_account'])->name('app-user-view-account');
    Route::get('user/view/security', [AppsController::class, 'user_view_security'])->name('app-user-view-security');
    Route::get('user/view/billing', [AppsController::class, 'user_view_billing'])->name('app-user-view-billing');
    Route::get('user/view/notifications', [AppsController::class, 'user_view_notifications'])->name('app-user-view-notifications');
    Route::get('user/view/connections', [AppsController::class, 'user_view_connections'])->name('app-user-view-connections');
});
/* Route Apps */

/* Route UI */
Route::group(['prefix' => 'ui'], function () {
    Route::get('typography', [UserInterfaceController::class, 'typography'])->name('ui-typography');
});
/* Route UI */

/* Route Icons */
Route::group(['prefix' => 'icons'], function () {
    Route::get('feather', [UserInterfaceController::class, 'icons_feather'])->name('icons-feather');
});
/* Route Icons */

/* Route Cards */
Route::group(['prefix' => 'card'], function () {
    Route::get('basic', [CardsController::class, 'card_basic'])->name('card-basic');
    Route::get('advance', [CardsController::class, 'card_advance'])->name('card-advance');
    Route::get('statistics', [CardsController::class, 'card_statistics'])->name('card-statistics');
    Route::get('analytics', [CardsController::class, 'card_analytics'])->name('card-analytics');
    Route::get('actions', [CardsController::class, 'card_actions'])->name('card-actions');
});
/* Route Cards */

/* Route Components */
Route::group(['prefix' => 'component'], function () {
    Route::get('accordion', [ComponentsController::class, 'accordion'])->name('component-accordion');
    Route::get('alert', [ComponentsController::class, 'alert'])->name('component-alert');
    Route::get('avatar', [ComponentsController::class, 'avatar'])->name('component-avatar');
    Route::get('badges', [ComponentsController::class, 'badges'])->name('component-badges');
    Route::get('breadcrumbs', [ComponentsController::class, 'breadcrumbs'])->name('component-breadcrumbs');
    Route::get('buttons', [ComponentsController::class, 'buttons'])->name('component-buttons');
    Route::get('carousel', [ComponentsController::class, 'carousel'])->name('component-carousel');
    Route::get('collapse', [ComponentsController::class, 'collapse'])->name('component-collapse');
    Route::get('divider', [ComponentsController::class, 'divider'])->name('component-divider');
    Route::get('dropdowns', [ComponentsController::class, 'dropdowns'])->name('component-dropdowns');
    Route::get('list-group', [ComponentsController::class, 'list_group'])->name('component-list-group');
    Route::get('modals', [ComponentsController::class, 'modals'])->name('component-modals');
    Route::get('pagination', [ComponentsController::class, 'pagination'])->name('component-pagination');
    Route::get('navs', [ComponentsController::class, 'navs'])->name('component-navs');
    Route::get('offcanvas', [ComponentsController::class, 'offcanvas'])->name('component-offcanvas');
    Route::get('tabs', [ComponentsController::class, 'tabs'])->name('component-tabs');
    Route::get('timeline', [ComponentsController::class, 'timeline'])->name('component-timeline');
    Route::get('pills', [ComponentsController::class, 'pills'])->name('component-pills');
    Route::get('tooltips', [ComponentsController::class, 'tooltips'])->name('component-tooltips');
    Route::get('popovers', [ComponentsController::class, 'popovers'])->name('component-popovers');
    Route::get('pill-badges', [ComponentsController::class, 'pill_badges'])->name('component-pill-badges');
    Route::get('progress', [ComponentsController::class, 'progress'])->name('component-progress');
    Route::get('spinner', [ComponentsController::class, 'spinner'])->name('component-spinner');
    Route::get('toast', [ComponentsController::class, 'toast'])->name('component-bs-toast');
});
/* Route Components */

/* Route Extensions */
Route::group(['prefix' => 'ext-component'], function () {
    Route::get('sweet-alerts', [ExtensionController::class, 'sweet_alert'])->name('ext-component-sweet-alerts');
    Route::get('block-ui', [ExtensionController::class, 'block_ui'])->name('ext-component-block-ui');
    Route::get('toastr', [ExtensionController::class, 'toastr'])->name('ext-component-toastr');
    Route::get('sliders', [ExtensionController::class, 'sliders'])->name('ext-component-sliders');
    Route::get('drag-drop', [ExtensionController::class, 'drag_drop'])->name('ext-component-drag-drop');
    Route::get('tour', [ExtensionController::class, 'tour'])->name('ext-component-tour');
    Route::get('clipboard', [ExtensionController::class, 'clipboard'])->name('ext-component-clipboard');
    Route::get('plyr', [ExtensionController::class, 'plyr'])->name('ext-component-plyr');
    Route::get('context-menu', [ExtensionController::class, 'context_menu'])->name('ext-component-context-menu');
    Route::get('swiper', [ExtensionController::class, 'swiper'])->name('ext-component-swiper');
    Route::get('tree', [ExtensionController::class, 'tree'])->name('ext-component-tree');
    Route::get('ratings', [ExtensionController::class, 'ratings'])->name('ext-component-ratings');
    Route::get('locale', [ExtensionController::class, 'locale'])->name('ext-component-locale');
});
/* Route Extensions */

/* Route Page Layouts */
Route::group(['prefix' => 'page-layouts'], function () {
    Route::get('collapsed-menu', [PageLayoutController::class, 'layout_collapsed_menu'])->name('layout-collapsed-menu');
    Route::get('full', [PageLayoutController::class, 'layout_full'])->name('layout-full');
    Route::get('without-menu', [PageLayoutController::class, 'layout_without_menu'])->name('layout-without-menu');
    Route::get('empty', [PageLayoutController::class, 'layout_empty'])->name('layout-empty');
    Route::get('blank', [PageLayoutController::class, 'layout_blank'])->name('layout-blank');
});
/* Route Page Layouts */

/* Route Forms */
Route::group(['prefix' => 'form'], function () {
    Route::get('input', [FormsController::class, 'input'])->name('form-input');
    Route::get('input-groups', [FormsController::class, 'input_groups'])->name('form-input-groups');
    Route::get('input-mask', [FormsController::class, 'input_mask'])->name('form-input-mask');

app/Models/CustomerMeeting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class CustomerMeeting extends Model
{
    use SoftDeletes, HasFactory, Notifiable;

    protected $fillable = ['customer_id', 'location', 'member', 'meeting_at', 'meeting_update', 'user_id'];

    protected $dates = [ 'meeting_at' ]; 

    protected $with = ['customer'];

    protected $appends = ['user_name'];

    public function customer()
    {
        return $this->belongsTo(Customer::class, 'customer_id');
    }

    public function documents()
    {
        return $this->hasMany(CustomerMeetingDocument::class, 'meeting_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getCustomerNameAttribute()
    {
        return $this->customer->company_name;
    }

    public function getUserNameAttribute()
    {
        return $this->user->name;
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\CustomerActivity;
use App\Models\CustomerMeeting;
use Carbon\Carbon;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
  // Dashboard - Analytics
  public function dashboardAnalytics()
  {
    $pageConfigs = ['pageHeader' => false];

    return view('/content/dashboard/dashboard-analytics', ['pageConfigs' => $pageConfigs]);
  }

  // Dashboard - Ecommerce
  public function dashboardEcommerce()
  {
    $pageConfigs = ['pageHeader' => false];

    return view('/content/dashboard/dashboard-ecommerce', ['pageConfigs' => $pageConfigs]);
  }

  // Dashboard - Document Management System
  public function dashboardDocumentManagement(Customer $customer)
  {
    $meetings = CustomerMeeting::all();
    $activities = CustomerActivity::all();
    $today = Carbon::today();
    $tomorrow = Carbon::tomorrow();
    $notifications = auth()->user()->unreadNotifications ?? [];

    $todayMeetings = CustomerMeeting::whereDate('meeting_at', $today)->get();
    $tomorrowMeetings = CustomerMeeting::whereDate('meeting_at', $tomorrow)->get();

    $pageConfigs = ['pageHeader' => false];

    return view('/content/dashboard/dashboard-documents-management', compact('pageConfigs', 'meetings', 'customer', 'today', 'tomorrow', 'todayMeetings', 'tomorrowMeetings', 'notifications', 'activities'));
  }
}

resources/views/content/dashboard/dashboard-documents-management.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Dashboard Ecommerce')

@section('vendor-style')
  {{-- vendor css files --}}
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/charts/apexcharts.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/toastr.min.css')) }}">
@endsection
@section('page-style')
  {{-- Page css files --}}
  <link rel="stylesheet" href="{{ asset(mix('css/base/pages/dashboard-ecommerce.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/charts/chart-apex.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/extensions/ext-component-toastr.css')) }}">
@endsection

@section('content')
<!-- Dashboard Ecommerce Starts -->
<section id="dashboard-ecommerce">
    <div class="row match-height">
        <!-- Developer Meetup Card -->
        <div class="col-lg-6 col-12">
            <div class="card card-developer-meetup">
                <div class="meetup-img-wrapper rounded-top text-center">
                    <img src="{{asset('images/illustration/api.svg')}}" alt="Meeting Pic" height="170" />
                </div>
                <div class="card-body">
                    <div class="meetup-header d-flex align-items-center">
                        <div class="meetup-day">
                            <h6 class="mb-0">{{ $today->format('l') }}</h6>
                            <h3 class="mb-0">{{ $today->format('d') }}</h3>
                        </div>
                        <div class="my-auto">
                            <h4 class="card-title mb-25">Today's Meeting</h4>
                        </div>
                    </div>
                    <div class="mt-0">
                        <div class="avatar float-start bg-light-primary rounded me-1">
                            <div class="avatar-content">
                                <i data-feather="calendar" class="avatar-icon font-medium-3"></i>
                            </div>
                        </div>
                        <div class="more-info">
                            <h6 class="mb-1">{{ $today->format('l, M d, Y') }}</h6>
                        </div>
                    </div>
                    @foreach ( $todayMeetings as $today )
                    <div class="mt-2">
                        <div class="avatar float-start bg-light-primary rounded me-1">
                            <div class="avatar-content">
                                <i data-feather="bookmark" class="avatar-icon font-medium-3"></i>
                            </div>
                        </div>
                        <div class="more-info">
                            <h6>{{ $today->customer_name }} at {{ $today->location }}</h6>
                        </div>
                    </div>
                    @endforeach

                    @if (count($todayMeetings) == 0)
                    <tr>
                        <td class="border-t px-6 py-4 text-center" colspan="6">You have no meeting today</td>
                    </tr>
                    @endif
                </div>

            </div>
        </div>
        <!--/ Developer Meetup Card -->

        <!-- Developer Meetup Card -->
        <div class="col-lg-6 col-12">
            <div class="card card-developer-meetup">
                <div class="meetup-img-wrapper rounded-top text-center">
                    <img src="{{asset('images/illustration/personalization.svg')}}" alt="Meeting Pic" height="170" />
                </div>
                <div class="card-body">
                    <div class="meetup-header d-flex align-items-center">
                        <div class="meetup-day">
                            <h6 class="mb-0">{{ $tomorrow->format('l') }}</h6>
                            <h3 class="mb-0">{{ $tomorrow->format('d') }}</h3>
                        </div>
                        <div class="my-auto">
                            <h4 class="card-title mb-25">Tomorrow's Meeting</h4>
                        </div>
                    </div>
                    <div class="mt-0">
                        <div class="avatar float-start bg-light-primary rounded me-1">
                            <div class="avatar-content">
                                <i data-feather="calendar" class="avatar-icon font-medium-3"></i>
                            </div>
                        </div>
                        <div class="more-info">
                            <h6 class="mb-1">{{ $tomorrow->format('l, M d, Y') }}</h6>
                        </div>
                    </div>
                    @foreach ( $tomorrowMeetings as $tomorrow )
                    <div class="mt-2">
                        <div class="avatar float-start bg-light-primary rounded me-1">
                            <div class="avatar-content">
                                <i data-feather="bookmark" class="avatar-icon font-medium-3"></i>
                            </div>
                        </div>
                        <div class="more-info">
                            <h6>{{ $tomorrow->customer_name }} at {{ $tomorrow->location }}</h6>
                        </div>
                    </div>
                    @endforeach

                    @if (count($tomorrowMeetings) == 0)
                    <tr>
                        <td class="border-t px-6 py-4 text-center" colspan="6">You have no meeting tomorrow</td>
                    </tr>
                    @endif
                </div>
            </div>
        </div>
        <!--/ Developer Meetup Card -->
    </div>

    <div class="row match-height">
        <div class="col-lg-4 col-12">
            <!-- User Card -->
            <div class="card">
                <div class="border-bottom">
                    <div class="alert-body d-flex align-items-center justify-content-between flex-wrap p-2">
                        <div class="me-1">
                            <h4 class="card-title">Activities Timeline</h4>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <ul class="timeline">
                        @foreach ( $activities as $data )
                        <li class="timeline-item">
                            <span class="timeline-point timeline-point-indicator"></span>
                            <div class="timeline-event">
                                <div class="d-flex justify-content-between flex-sm-row flex-column mb-sm-0 mb-1">
                                    <h6>{{ $data->activity }}</h6>
                                    <span class="timeline-event-time"></span>
                                </div>
                            </div>
                        </li>
                        @endforeach
                    </ul>
                </div>
            </div>
            <!-- /User Card -->
        </div>
        <!-- Company Table Card -->
        <div class="col-lg-8 col-12">
            <div class="card card-company-table">
                <div class="border-bottom">
                    <div class="alert-body d-flex align-items-center justify-content-between flex-wrap p-2">
                        <div class="me-1">
                            <h4 class="card-title">List of Meetings</h4>
                        </div>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Company Name</th>
                            <th>Date</th>
                            <th>Location</th>
                        </tr>
                        @foreach ($meetings as $meeting)
                        <tr class="align-top">
                            <td>{{ $meeting->customer_name }}</td>
                            <td>{{ Carbon\Carbon::parse($meeting->meeting_at)->format('l - d M Y')  }}</td>
                            <td>{{ $meeting->location }}</td>
                        </tr>
                        @endforeach

                        @if (count($meetings) == 0)
                        <tr>
                            <td class="border-t px-6 py-4 text-center" colspan="6">You have no meeting</td>
                        </tr>
                        @endif
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!-- Dashboard Ecommerce ends -->
@endsection

@section('vendor-script')
  {{-- vendor files --}}
  <script src="{{ asset(mix('vendors/js/charts/apexcharts.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/extensions/toastr.min.js')) }}"></script>
@endsection
@section('page-script')
  {{-- Page js files --}}
  <script src="{{ asset(mix('js/scripts/pages/dashboard-ecommerce.js')) }}"></script>
@endsection